package com.FXTracker.response;

public enum Function {

    GLOBAL_QUOTE,
    SYMBOL_SEARCH,
    TIME_SERIES_INTRADAY,
    TIME_SERIES_DAILY,
    TIME_SERIES_DAILY_ADJUSTED,
    TIME_SERIES_WEEKLY,
    TIME_SERIES_WEEKLY_ADJUSTED,
    TIME_SERIES_MONTHLY,
    TIME_SERIES_MONTHLY_ADJUSTED,
    REALTIME_BULK_QUOTES,
    MARKET_STATUS,
    TOP_GAINERS_LOSERS,
    OVERVIEW,
    DIVIDENDS,
    CURRENCY_EXCHANGE_RATE;



}
