spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?authSource=${DB_USER}

  application:
    name: Investment-Management

  jackson:
    serialization:
      INDENT_OUTPUT: true

  output:
    ansi:
      enabled: always

server:
  servlet:
    session:
      timeout: 2m

alphavantage:
  api:
    key: ${API_KEY}
    url: https://www.alphavantage.co/query

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

logging:
  file:
    name: logs/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  level:
    root: WARN
    com.FXTracker: INFO
    org.springframework: WARN
    org.mongodb.driver: WARN
    org.springframework.data.mongodb: DEBUG


