spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    mongodb:
      uri: mongodb://admin:stocks1234@localhost:27017/stocks?authSource=admin
      port: 27017

  application:
    name: Investment-Management

  jackson:
    serialization:
      INDENT_OUTPUT: true

  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    session:
      timeout: 2m

alphavantage:
  api:
    key: 6FZME81OT4D69JJV
    url: https://www.alphavantage.co/query
    
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

logging:
  file:
    path: logs
    name: logs/application.log
    pattern:
      file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  level:
    root: WARN
    com.FXTracker: INFO
    org.springframework: WARN
    org.mongodb.driver: WARN
    org.springframework.data.mongodb: DEBUG


